### PR TITLE
fixing iOS load issue with react native 0.56

### PR DESCRIPTION
**Pull request by virdesai**

### CODE REVIEW

**Comment by Marcsimm** [comment]
When can this be merged? this is quite urgent for us?

**Comment by virdesai** [comment]
I don't have the ability to merge it otherwise I would

**Comment by seekshiva** [comment]
@virdesai Sorry for the delay. Can you provide more detail about how this change helps or the problem it solves?

Thanks

**Comment by joerichsen** [comment]
I had the same problem after upgrading to 0.56 and the solution that @virdesai provides solves it 👍 

The issue is described here https://github.com/facebook/react-native/issues/19986

Maybe it is the source of the problem in this issue as well?
https://github.com/seekshiva/react-native-remote-svg/issues/19

**Pull request merged**
